# Generated by Django 4.2.4 on 2023-08-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patientname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
