# Generated by Django 4.2.4 on 2023-08-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthome',
            old_name='problem',
            new_name='describe',
        ),
    ]
