# Generated by Django 4.2.4 on 2023-08-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_problem_patienthome_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthome',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
