# Generated by Django 4.2.4 on 2023-08-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patienthome_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthome',
            old_name='Patientname',
            new_name='name',
        ),
    ]
