# Generated by Django 4.2.4 on 2023-08-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_patientname_patienthome_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientHome',
            new_name='PatientHomes',
        ),
    ]
