# Generated by Django 4.2.4 on 2023-08-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_patienthome_patienthomes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthomes',
            old_name='mobile',
            new_name='contact',
        ),
    ]
