# Generated by Django 4.2.4 on 2023-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_mobile_patienthomes_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthomes',
            name='describe',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
