# Generated by Django 4.2.4 on 2023-08-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_patienthomes_describe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientHomes',
            new_name='Patients',
        ),
    ]
